- id: plantuml-generate-svg
  name: generate svg from plantuml
  description: Generate SVG files for all PlantUML files
  entry: plantuml-generate-svg
  require_serial: true
  language: python
  files: \.(puml)$
